springdoc:
  swagger-ui:
    custom-css-url: /swagger-ui/swagger-overrides.css
spring:
  main:
    allow-circular-references: true



  data:
#    redis:
#      host: redis-11059.crce182.ap-south-1-1.ec2.redns.redis-cloud.com
#      port: 11059
#      password: i14wXExhlSuAwjf1PJRY5zFOpFSuqJ0A
    mongodb:
      uri: ${MONGODB_URI}
      database: jobportal
      auto-index-creation: true
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}

server:
  port: 8080
  servlet:
    context-path: /jobPortal



